In [2]:
import numpy as np

# array(배열)의 종류

## 1차원 배열

벡터

In [6]:
arr_1d=np.array([1,2,3,4,5,6,7,8])
print(arr_1d)

[1 2 3 4 5 6 7 8]


## 2차원 배열

행렬

In [8]:
arr_2d=arr_1d.reshape((2,4))
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


## 3차원 이상 배열

텐서(tensor)

In [1]:
arr_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3d)

NameError: name 'np' is not defined

# 1차원 array와 list 비교

## 원소의 동질성

- array: 원소들의 데이터타입이 모두 같아야함
- list: 원소들의 데이터타입이 달라도 됨

In [13]:
l3=[12,455,63.3,True,'abc']
l3

[12, 455, 63.3, True, 'abc']

In [15]:
#array는 데이터타입이 모두 같아야해서, 자동으로 하나로 통일되어 바뀜
b=np.array(l3)
print(b)

['12' '455' '63.3' 'True' 'abc']


- cf) type과 dtype차이
- type:변수의 데이터타입
- dtype: 변수를 구성하는 원소(예:array의 구성요소)의 데이터타입

In [16]:
type(np.array([1,2,3]))

numpy.ndarray

In [17]:
np.array([1,2,3]).dtype

dtype('int32')

## 계산의 편의성

### 동시연산 가능성

- array: 동시연산 가능
- list: 동시연산이 아니라 list연산이 이루어짐

In [3]:
#array:동시연산 가능
aArray=[2,4,6,8]
aArray=np.array(aArray)
a3Array=aArray*-3

In [4]:
print(a3Array)

[ -6 -12 -18 -24]


In [9]:
#list:동시연산X, list연산O
aList=[2,4,6,8]
aList*2


[2, 4, 6, 8, 2, 4, 6, 8]

### 연산처리의 차이

- array: array구성하는 원소들의 연산으로 처리
- list: list자체의 연산

In [32]:
#array: 원소들의 값을 더함
np.array([1,2,3])+np.array([10,20,30])

array([11, 22, 33])

In [33]:
#list: 리스트를 서로 합침
[1,2,3]+[10,20,30]

[1, 2, 3, 10, 20, 30]

# array 생성 함수들

## 연속된 값으로 만들어진 array

In [36]:
#range사용해서 array만들기
a15=np.array(range(0,15))
a15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
#arange사용해서 array만들기
a15p=np.arange(0,15)
a15p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 0으로 구성된 array

np.zeros

In [40]:
zA=np.zeros(5)
zA

array([0., 0., 0., 0., 0.])

In [41]:
zA2=np.zeros((5,2))
zA2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## 1로 구성된 array

np.ones

In [43]:
oA=np.ones(4)
oA

array([1., 1., 1., 1.])

In [44]:
oA2=np.ones((2,5))
oA2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# array(배열)의 조작

## 배열 특정 위치의 값 바꾸기

arr_2d[]=새로운 값

In [47]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])

In [49]:
arr_2d[1,2]=99
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6, 99,  8]])

In [50]:
arr_2d[:,1]=77
arr_2d

array([[ 1, 77,  3,  4],
       [ 5, 77, 99,  8]])

## 원소의 추가 및 삭제

- numpy의 함수사용해야됨
- 왜냐면, list의 .insert(), .pop()같은 array자체 함수 X
- 원래 배열 바뀌지 않음(변경된 배열 저장 위해서는 별도 저장해야 함)
-
- 배열에 원소의 추가 및 삭제는 자주 사용x(배열은 계산을 위해 주로 사용/배열을 가공하여 새로운 배열 생성)

### 배열에 원소 추가

- axis(행이나 열) 지정
- 지정하지 않으면 1차원 배열로 변환하여 처리

In [57]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
np.insert(arr_2d,1,9,axis=1) #1열에 9 넣기

array([[1, 9, 2, 3, 4],
       [5, 9, 6, 7, 8]])

In [62]:
np.insert(arr_2d,1,9,axis=0) #1행에 9 넣기

array([[1, 2, 3, 4],
       [9, 9, 9, 9],
       [5, 6, 7, 8]])

In [64]:
np.insert(arr_2d,1,9)

array([1, 9, 2, 3, 4, 5, 6, 7, 8])

### 배열에 원소 삭제

- axis(행이나 열) 지정
- 지정하지 않으면 1차원 배열로 변환하여 처리

In [67]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
np.delete(arr_2d,[0,2],axis=1) #0열과 2열 삭제

array([[2, 4],
       [6, 8]])

In [72]:
np.delete(arr_2d,0,axis=0) #0행 삭제

array([[5, 6, 7, 8]])

In [73]:
np.delete(arr_2d,0) #axis지정안하면 1차원으로 늘어뜨린담에 0번째 삭제

array([2, 3, 4, 5, 6, 7, 8])

In [76]:
np.delete(arr_2d,[0,2])#axis지정안하면 1차원으로 늘어뜨린담에 0번째,2번째 삭제

array([2, 4, 5, 6, 7, 8])

# Sub-array(부분배열)

- array의 연속된 부분
- 복사(copy)가 아님 ==> 뷰(view)
- array의 연속된 일부에 대한 새로운 이름 부여임
- subarray값 변경시, array값 변경
- 다만, subarray의 계산 값을 다른 이름에 저장시(같은 이름이라도 문장 구조상 다른 이름에 저장하는 형식), 복사로 취급

In [78]:
a1=np.array([1,3,5,7,9])

In [79]:
sa=a1[2:4]

In [80]:
sa

array([5, 7])

In [86]:
# sub-array변경시, array값변경

In [85]:
sa[:]=sa[:]*(-1) #같은 표현: sa *= -1

In [82]:
sa

array([-5, -7])

In [83]:
a1

array([ 1,  3, -5, -7,  9])

In [87]:
# subarray계산 값을 다른 이름에 저장시, 복사로 취급

In [88]:
a1

array([1, 3, 5, 7, 9])

In [89]:
sa=a1[2:4]

In [90]:
sa

array([5, 7])

In [91]:
sa=sa*-1

In [92]:
sa

array([-5, -7])

In [93]:
a1

array([1, 3, 5, 7, 9])

## Sub-array아닌 경우

- sub-array: array의 연속된 일부
- 연속되지 않은 일부에 새로운 이름 부여할 경우=>복사(copy)로 처리

In [137]:
A=np.array([[10,11,12,13],
           [14,15,16,17],
           [18,19,20,21],
           [22,23,24,25]])
A

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [143]:
#배열 슬라이싱하면 view됨(원본영향O)
sub_A=A[1:3,1:3]
sub_A

array([[15, 16],
       [19, 20]])

In [145]:
sub_A*=-2

In [146]:
sub_A

array([[-30, -32],
       [-38, -40]])

In [147]:
A

array([[ 10,  11,  12,  13],
       [ 14, -30, -32,  17],
       [ 18, -38, -40,  21],
       [ 22,  23,  24,  25]])

In [148]:
A=np.array([[10,11,12,13],
           [14,15,16,17],
           [18,19,20,21],
           [22,23,24,25]])
A

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [159]:
sub_A2=A[[1,3],1:3] #sub-array 아님=>원본영향X(copy)
sub_A2

array([[15, 16],
       [23, 24]])

In [156]:
sub_A2*=-2

In [157]:
sub_A2

array([[-30, -32],
       [-46, -48]])

In [158]:
A

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

## 2차원 array

- 각각의 axis별로 index의 값 또는 범위

In [130]:
myMatrix=np.array([[0,1,2,3,4,5,6,7],
         [8,9,10,11,12,13,14,15],
         [16,17,18,19,20,21,22,23],
        [24,25,26,27,28,29,30,31],
       [32,33,34,35,36,37,38,39]           ])
myMatrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [131]:
myMatrix[2,:]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [132]:
myMatrix[2]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [133]:
myMatrix[2,]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [134]:
myMatrix[:,0]

array([ 0,  8, 16, 24, 32])

In [135]:
myMatrix[,0] #행에 반드시 입력해야됨

SyntaxError: invalid syntax (1957316875.py, line 1)

# view와 copy

## 리스트

### View

- 원본에 영향O
- 하나의 list를 두 변수가 공유하는 형식

In [96]:
my_num=[10,20,30,40]
my_copy=my_num
my_copy[2]*=-1

In [97]:
my_copy

[10, 20, -30, 40]

In [98]:
my_num

[10, 20, -30, 40]

### Copy

- 원본에 영향X
- 복사본 만든 것

In [101]:
my_num=[10,20,30,40]
my_copy=my_num.copy()
my_copy[2]*=-1

In [102]:
my_copy

[10, 20, -30, 40]

In [103]:
my_num

[10, 20, 30, 40]

In [104]:
my_num=[10,20,30,40]
my_copy=my_num[:]
my_copy[2]*=-1

In [105]:
my_copy

[10, 20, -30, 40]

In [106]:
my_num

[10, 20, 30, 40]

## 배열

### View

- 원본에 영향O
- 하나의 array를 두 변수가 공유하는 식

In [109]:
my_arr=np.array([10,20,30,40])
my_copy=my_arr
my_copy[2]*=-1

In [110]:
my_copy

array([ 10,  20, -30,  40])

In [111]:
my_arr

array([ 10,  20, -30,  40])

In [113]:
my_arr=np.array([10,20,30,40])
my_copy=my_arr[:]
my_copy[2]*=-1

In [114]:
my_copy

array([ 10,  20, -30,  40])

In [115]:
my_arr

array([ 10,  20, -30,  40])

### Copy

- 원본에 영향O
- 복사본 만든 것

In [117]:
my_arr=np.array([10,20,30,40])
my_copy=my_arr.copy()
my_copy[2]*=-1

In [118]:
my_copy

array([ 10,  20, -30,  40])

In [119]:
my_arr

array([10, 20, 30, 40])

## 리스트와 배열 차이점

- 리스트는 view방식으로 새로운 변수에 할당
        copy방식으로 [:] 슬라이싱, copy()함수사용
- 배열은 view방식으로 새로운 변수 할당, [:] 슬라이싱
        copy방식으로 copy()함수사용

# Array filtering

- 배열에서 조건을 만족시키는 원소들만 선별(filtering)
- True/False값을 갖는 조건식 작성
- 조건식을 배열에 적용하면, element-wise연산에 의해 각원소들이 조건식을 만족시키는 결과 계산됨
- 조건식의 계산 결과를 배열의 인덱스에 적용하면, True인 원소들만 선별(filter)됨
- 2차원 이상의 배열은 1차원 배열로 자동으로 바뀌어져 출력됨

In [161]:
my_array=np.array([2,-3,-5,9,7])
my_array>=0

array([ True, False, False,  True,  True])

In [162]:
my_array[my_array>=0]

array([2, 9, 7])

In [163]:
ns=np.array([[19,11,17],
            [9,20,15],
            [36,7,18]])
print(ns)

[[19 11 17]
 [ 9 20 15]
 [36  7 18]]


In [164]:
ns>=15

array([[ True, False,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [165]:
ns[ns>=15]

array([19, 17, 20, 15, 36, 18])

# Array의 변환 및 계산

- 범용함수(numpy함수)

- np.sqrt()
- np.abs()
- np.sum()
- np.max()
- np.min()
- np.mean()
- np.std()
- np.sort()

In [168]:
my_a=np.array([1,-9,16,-4,20])

In [169]:
my_abs=np.abs(my_a)
my_abs

array([ 1,  9, 16,  4, 20])

In [170]:
print(np.sqrt(my_a))

[1.                nan 4.                nan 4.47213595]


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_33424\467157276.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(my_a))


# Array의 계산과 좌표축

- axis=0 적용 시, 열 축에 따라서 통계값 계산됨
- axis=1 적용 시, 행 축에 따라서 통계값 계산됨

## 

In [171]:
A=np.array([[10,11,12,13],
           [14,15,16,17],
           [18,19,20,21],
           [22,23,24,25]])
A

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [172]:
A.sum()

280

In [173]:
A.sum(axis=0)

array([64, 68, 72, 76])

In [174]:
np.sum(A,axis=0) #위와 동일 표현

array([64, 68, 72, 76])

In [175]:
A.mean(axis=1)

array([11.5, 15.5, 19.5, 23.5])

In [176]:
np.mean(A,axis=1)#위와 동일 표현

array([11.5, 15.5, 19.5, 23.5])

## np.apply_over_axes

- 2차원배열 형태로 결과 도출 가능

In [179]:
np.apply_over_axes(np.mean,a=A,axes=1)

array([[11.5],
       [15.5],
       [19.5],
       [23.5]])

In [180]:
(np.apply_over_axes(np.mean,a=A,axes=1)).shape

(4, 1)

In [181]:
np.apply_over_axes(np.mean,a=A,axes=0)

array([[16., 17., 18., 19.]])

In [182]:
(np.apply_over_axes(np.mean,a=A,axes=0)).shape

(1, 4)

In [183]:
arr_3d=np.ones([4,4,4])
arr_3d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [184]:
arr_3d_z=np.apply_over_axes(np.sum,arr_3d,axes=[0,1])

In [185]:
print(arr_3d_z)

[[[16. 16. 16. 16.]]]


In [186]:
arr_3d_z[0,0,1]

16.0

# 행렬 및 벡터 계산

## 행렬곱(A·B)

- 두 행렬의 내적을 계산
- 1번째 행렬의 열의 수와 2번째 행렬의 행의 수가 같아야 함

In [189]:
A=np.array([[1,10],[2,20],[3,30]])
B=np.array([[1,2,3],[1,2,3]])
C=np.dot(A,B)

In [190]:
print(C)

[[11 22 33]
 [22 44 66]
 [33 66 99]]


## 곱셈(A*B)

- 원소별 곱셈
- 브로드캐스터
:두 행렬의 행,열 크기 동일해야 함.
-> 두 행과 열의 수가 맞지 않으면, 작은 행렬의 행이나 열을 늘려서 큰 행렬의 행과 열의 수와 같이 만든 후 연산처리
-> 작은 행렬의 행이나 열의 수를 곱하면 큰 행렬의 행과 열의 수가 될 수 있어야 함

In [192]:
A=np.array([[1,10],[2,20],[3,30]])
B2=np.array([[1,2],[1,2]])

In [193]:
C_prod=A*B2

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [194]:
B3=np.array([[1,2]])

In [195]:
C_prod=A*B3
print(C_prod)

[[ 1 20]
 [ 2 40]
 [ 3 60]]


## 벡터의 크기(norm)

- n차원 공간에서 벡터의 길이
- 요소의 제곱값을 더해서 제곱근 계산

In [198]:
A=np.array([1,2])
np.linalg.norm(A)

2.23606797749979

# shape과 reshape

- .shape : 행&열 개수 나타내기
- .reshape() : 행&열 개수 바꾸기

In [202]:
A=np.array([[1,10],[2,20],[3,30]])

In [204]:
A.shape

(3, 2)

In [208]:
A.reshape(2,3) #reshape시 개수 안맞으면 에러

array([[ 1, 10,  2],
       [20,  3, 30]])

In [207]:
A.reshape(2,3,1)

array([[[ 1],
        [10],
        [ 2]],

       [[20],
        [ 3],
        [30]]])